lijiajia3515:
  auth:
    server: auth2.hfhksoft.com
    client:
      id: hfhk_auth
      client-id: hfhk_auth
      client-secret: hfhk_auth
      scopes:
        - default
  mongo:
    database: lijiajia3515-auth
    gridfs:
      database: lijiajia3515-auth
      bucket: lijiajia3515
    authentication-database: lijiajia3515
    host: 192.168.30.22
    port: 27017
    username: lijiajia3515
    password: lijiajia3515
  redis:
    database: 1
    host: 192.168.30.22
    port: 6379
    username: lijiajia3515
    password: lijiajia3515
  consul:
    host: 192.168.30.22
    port: 8500
    discovery:
      instance-zone: local
      instance-group: local

server:
  port: 10000
