lijiajia3515:
  auth:
    server: 127.0.0.1
    client:
      id: hfhk_auth
      client-id: hfhk_auth
      client-secret: hfhk_auth
      scopes:
        - default
  mongo:
    database: hfhk-auth
    gridfs:
      database: hfhk-auth
      bucket: hfhk-auth
    authentication-database: hfhk
    host: 192.168.30.22
    port: 27017
    username: hfhk
    password: Hfhk.1320.
  redis:
    database: 1
    host: 192.168.30.22
    port: 6379
    username: lijiajia3515
    password: lijiajia3515
  consul:
    host: 192.168.30.22
    port: 8500
    discovery:
      instance-zone: local
      instance-group: local

server:
  port: 10000

